fail_fast: true

repos:
  - repo: local
    hooks:
      - id: shellcheck
        priority: 0
        name: Lint Shell
        language: system
        types: [shell]
        entry: shellcheck
        args: ['-a', '-x', '-S', 'style']

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.12.1
    hooks:
    - id: commitizen
